# Generated by Django 6.0 on 2026-01-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdvertisementPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на YouTube'),
        ),
    ]
