# Generated by Django 6.0 on 2026-01-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='comments/'),
        ),
    ]
