# Generated by Django 6.0 on 2026-01-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_alter_group_options_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Чоловік'), ('female', 'Жінка')], max_length=30, null=True),
        ),
    ]
