# Generated by Django 6.0 on 2026-01-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
