# Generated by Django 6.0 on 2026-01-07 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0005_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Назва групи має містити принаймні 3 символи')]),
        ),
    ]
